name = "remoteshe-worker"
main = "src/index.ts"
compatibility_date = "2024-09-01"

[triggers]
crons = ["0 8 * * 1"]   # Every Monday at 8am UTC — refreshes job cache weekly

[[kv_namespaces]]
binding = "KV"
id = "f3af7363ca0d4115a6cc3f6317893fe2"

[vars]
FRONTEND_URL = "https://remoteshe.netlify.app"
