export interface Company {
  id: string
  name: string
  industry: string
  country: string
  remote_policy: string
  website: string
  maternity_leave_weeks: number | null
  paternity_leave_weeks: number | null
  ivf_coverage: boolean
  fertility_support: boolean
  childcare_support: boolean
  caregiver_leave: boolean
  women_leadership_percent: number | null
  carefolio_score: number
  verification_status: string
}

export const COMPANIES: Company[] = [
  { id: 'google', name: 'Google (Alphabet)', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.google.com', maternity_leave_weeks: 24, paternity_leave_weeks: 18, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 33, carefolio_score: 72, verification_status: 'verified' },
  { id: 'microsoft', name: 'Microsoft', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.microsoft.com', maternity_leave_weeks: 20, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 30, carefolio_score: 79, verification_status: 'verified' },
  { id: 'meta', name: 'Meta', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.metacareers.com', maternity_leave_weeks: 24, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 37, carefolio_score: 79, verification_status: 'verified' },
  { id: 'apple', name: 'Apple', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.apple.com/careers', maternity_leave_weeks: 18, paternity_leave_weeks: 6, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 30, carefolio_score: 57, verification_status: 'verified' },
  { id: 'salesforce', name: 'Salesforce', industry: 'Cloud Computing', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.salesforce.com/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 32, carefolio_score: 84, verification_status: 'verified' },
  { id: 'hubspot', name: 'HubSpot', industry: 'Technology', country: 'USA', remote_policy: 'Remote Flexible', website: 'https://www.hubspot.com/careers', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 60, verification_status: 'verified' },
  { id: 'atlassian', name: 'Atlassian', industry: 'Technology', country: 'Australia', remote_policy: 'Fully Remote', website: 'https://www.atlassian.com/company/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 20, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 36, carefolio_score: 95, verification_status: 'verified' },
  { id: 'automattic', name: 'Automattic', industry: 'Technology', country: 'USA', remote_policy: 'Fully Remote', website: 'https://automattic.com/work-with-us', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: false, fertility_support: false, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 55, verification_status: 'verified' },
  { id: 'gitlab', name: 'GitLab', industry: 'Technology', country: 'USA', remote_policy: 'Fully Remote', website: 'https://about.gitlab.com/jobs', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: false, fertility_support: true, childcare_support: false, caregiver_leave: true, women_leadership_percent: null, carefolio_score: 44, verification_status: 'verified' },
  { id: 'twilio', name: 'Twilio', industry: 'Technology', country: 'USA', remote_policy: 'Remote-first', website: 'https://www.twilio.com/en-us/company/jobs', maternity_leave_weeks: 16, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: 38, carefolio_score: 67, verification_status: 'verified' },
  { id: 'datadog', name: 'Datadog', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.datadoghq.com', maternity_leave_weeks: 16, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 64, verification_status: 'verified' },
  { id: 'elastic', name: 'Elastic', industry: 'Technology', country: 'Netherlands', remote_policy: 'Remote-first', website: 'https://www.elastic.co/careers', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: 30, carefolio_score: 59, verification_status: 'verified' },
  { id: 'canva', name: 'Canva', industry: 'Technology', country: 'Australia', remote_policy: 'Hybrid', website: 'https://www.canva.com/careers', maternity_leave_weeks: 18, paternity_leave_weeks: 18, ivf_coverage: false, fertility_support: false, childcare_support: true, caregiver_leave: false, women_leadership_percent: 44, carefolio_score: 54, verification_status: 'verified' },
  { id: 'stripe', name: 'Stripe', industry: 'Fintech', country: 'USA', remote_policy: 'Hybrid', website: 'https://stripe.com/jobs', maternity_leave_weeks: 20, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 65, verification_status: 'verified' },
  { id: 'adobe', name: 'Adobe', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.adobe.com/careers.html', maternity_leave_weeks: 26, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 30, carefolio_score: 84, verification_status: 'verified' },
  { id: 'cisco', name: 'Cisco', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://jobs.cisco.com', maternity_leave_weeks: 22, paternity_leave_weeks: 4, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 30, carefolio_score: 72, verification_status: 'verified' },
  { id: 'hpe', name: 'Hewlett Packard Enterprise', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.hpe.com/us/en/living-progress/employee-benefits.html', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 85, verification_status: 'verified' },
  { id: 'sas', name: 'SAS Institute', industry: 'Technology', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.sas.com/en_us/careers.html', maternity_leave_weeks: null, paternity_leave_weeks: null, ivf_coverage: false, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 40, verification_status: 'verified' },
  { id: 'spotify', name: 'Spotify', industry: 'Digital Media', country: 'Sweden', remote_policy: 'Fully Remote', website: 'https://www.lifeatspotify.com', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 83, verification_status: 'verified' },
  { id: 'netflix', name: 'Netflix', industry: 'Entertainment', country: 'USA', remote_policy: 'Hybrid', website: 'https://jobs.netflix.com', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 70, verification_status: 'verified' },
  { id: 'airbnb', name: 'Airbnb', industry: 'Hospitality Technology', country: 'USA', remote_policy: 'Fully Remote', website: 'https://careers.airbnb.com', maternity_leave_weeks: 22, paternity_leave_weeks: 10, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 87, verification_status: 'verified' },
  { id: 'shopify', name: 'Shopify', industry: 'E-commerce', country: 'Canada', remote_policy: 'Remote-first', website: 'https://www.shopify.com/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 18, ivf_coverage: false, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 71, verification_status: 'verified' },
  { id: 'etsy', name: 'Etsy', industry: 'E-commerce', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.etsy.com', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 95, verification_status: 'verified' },
  { id: 'citigroup', name: 'Citigroup', industry: 'Financial Services', country: 'USA', remote_policy: 'Hybrid', website: 'https://jobs.citi.com', maternity_leave_weeks: 24, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 51, carefolio_score: 82, verification_status: 'verified' },
  { id: 'goldman-sachs', name: 'Goldman Sachs', industry: 'Financial Services', country: 'USA', remote_policy: 'In-office', website: 'https://www.goldmansachs.com/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 37, carefolio_score: 87, verification_status: 'verified' },
  { id: 'jpmorgan', name: 'JPMorgan Chase', industry: 'Financial Services', country: 'USA', remote_policy: 'In-office', website: 'https://careers.jpmorgan.com', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 49, carefolio_score: 69, verification_status: 'verified' },
  { id: 'bofa', name: 'Bank of America', industry: 'Financial Services', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.bankofamerica.com', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 55, carefolio_score: 74, verification_status: 'verified' },
  { id: 'hsbc', name: 'HSBC', industry: 'Financial Services', country: 'UK', remote_policy: 'Hybrid', website: 'https://www.hsbc.com/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 4, ivf_coverage: false, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: 35, carefolio_score: 67, verification_status: 'verified' },
  { id: 'sp-global', name: 'S&P Global', industry: 'Financial Services', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.spglobal.com', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 33, carefolio_score: 92, verification_status: 'verified' },
  { id: 'wise', name: 'Wise', industry: 'Fintech', country: 'UK', remote_policy: 'Hybrid', website: 'https://wise.com/gb/careers', maternity_leave_weeks: 18, paternity_leave_weeks: 18, ivf_coverage: false, fertility_support: false, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 45, verification_status: 'verified' },
  { id: 'deloitte', name: 'Deloitte', industry: 'Professional Services', country: 'UK', remote_policy: 'Hybrid', website: 'https://www2.deloitte.com/global/en/careers.html', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 88, verification_status: 'verified' },
  { id: 'accenture', name: 'Accenture', industry: 'Professional Services', country: 'Ireland', remote_policy: 'Hybrid', website: 'https://www.accenture.com/us-en/careers', maternity_leave_weeks: 18, paternity_leave_weeks: 18, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 47, carefolio_score: 74, verification_status: 'verified' },
  { id: 'ey', name: 'EY', industry: 'Professional Services', country: 'UK', remote_policy: 'Hybrid', website: 'https://www.ey.com/en_us/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 45, carefolio_score: 95, verification_status: 'verified' },
  { id: 'pwc', name: 'PwC', industry: 'Professional Services', country: 'UK', remote_policy: 'Hybrid', website: 'https://www.pwc.com/us/en/careers.html', maternity_leave_weeks: 21, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 42, carefolio_score: 82, verification_status: 'verified' },
  { id: 'mckinsey', name: 'McKinsey & Company', industry: 'Consulting', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.mckinsey.com/careers', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 44, carefolio_score: 74, verification_status: 'verified' },
  { id: 'diageo', name: 'Diageo', industry: 'Consumer Goods', country: 'UK', remote_policy: 'Hybrid', website: 'https://www.diageo.com/en/careers', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 70, carefolio_score: 95, verification_status: 'verified' },
  { id: 'patagonia', name: 'Patagonia', industry: 'Retail', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.patagonia.com', maternity_leave_weeks: 16, paternity_leave_weeks: 12, ivf_coverage: false, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 64, verification_status: 'verified' },
  { id: 'unilever', name: 'Unilever', industry: 'Consumer Goods', country: 'UK', remote_policy: 'Hybrid', website: 'https://careers.unilever.com', maternity_leave_weeks: 16, paternity_leave_weeks: 6, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 67, verification_status: 'verified' },
  { id: 'nestle', name: 'Nestlé', industry: 'Food & Beverage', country: 'Switzerland', remote_policy: 'Hybrid', website: 'https://www.nestlejobs.com', maternity_leave_weeks: 18, paternity_leave_weeks: 4, ivf_coverage: false, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 48, carefolio_score: 57, verification_status: 'verified' },
  { id: 'pg', name: 'Procter & Gamble', industry: 'Consumer Goods', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.pgcareers.com', maternity_leave_weeks: 16, paternity_leave_weeks: 8, ivf_coverage: false, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 38, carefolio_score: 54, verification_status: 'verified' },
  { id: 'loreal', name: "L'Oréal", industry: 'Beauty & Cosmetics', country: 'France', remote_policy: 'Hybrid', website: 'https://careers.loreal.com', maternity_leave_weeks: 16, paternity_leave_weeks: 8, ivf_coverage: false, fertility_support: false, childcare_support: true, caregiver_leave: false, women_leadership_percent: 61, carefolio_score: 57, verification_status: 'verified' },
  { id: 'danone', name: 'Danone', industry: 'Food & Beverage', country: 'France', remote_policy: 'Hybrid', website: 'https://careers.danone.com', maternity_leave_weeks: 18, paternity_leave_weeks: null, ivf_coverage: false, fertility_support: false, childcare_support: true, caregiver_leave: false, women_leadership_percent: 42, carefolio_score: 57, verification_status: 'verified' },
  { id: 'ikea', name: 'IKEA', industry: 'Retail', country: 'Sweden', remote_policy: 'Hybrid', website: 'https://www.ikea.com/global/en/this-is-ikea/working-at-ikea', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: false, fertility_support: false, childcare_support: true, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 54, verification_status: 'verified' },
  { id: 'lululemon', name: 'Lululemon', industry: 'Retail', country: 'Canada', remote_policy: 'Hybrid', website: 'https://careers.lululemon.com', maternity_leave_weeks: 26, paternity_leave_weeks: 26, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: 50, carefolio_score: 80, verification_status: 'verified' },
  { id: 'jnj', name: 'Johnson & Johnson', industry: 'Healthcare', country: 'USA', remote_policy: 'Hybrid', website: 'https://www.careers.jnj.com', maternity_leave_weeks: 17, paternity_leave_weeks: 12, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: true, women_leadership_percent: null, carefolio_score: 64, verification_status: 'verified' },
  { id: 'novartis', name: 'Novartis', industry: 'Healthcare', country: 'Switzerland', remote_policy: 'Hybrid', website: 'https://www.novartis.com/careers', maternity_leave_weeks: 14, paternity_leave_weeks: 14, ivf_coverage: false, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 50, verification_status: 'verified' },
  { id: 'roche', name: 'Roche', industry: 'Healthcare', country: 'Switzerland', remote_policy: 'Hybrid', website: 'https://careers.roche.com', maternity_leave_weeks: 18, paternity_leave_weeks: 14, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 45, carefolio_score: 77, verification_status: 'verified' },
  { id: 'schneider', name: 'Schneider Electric', industry: 'Energy & Industrial', country: 'France', remote_policy: 'Hybrid', website: 'https://www.se.com/ww/en/about-us/careers', maternity_leave_weeks: 20, paternity_leave_weeks: 4, ivf_coverage: true, fertility_support: true, childcare_support: true, caregiver_leave: false, women_leadership_percent: 42, carefolio_score: 75, verification_status: 'verified' },
  // Two extra companies with public ATS boards (not in original seed but have Greenhouse)
  { id: 'figma', name: 'Figma', industry: 'Technology', country: 'USA', remote_policy: 'Remote Flexible', website: 'https://www.figma.com/careers', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 62, verification_status: 'verified' },
  { id: 'notion', name: 'Notion', industry: 'Technology', country: 'USA', remote_policy: 'Remote Flexible', website: 'https://www.notion.so/careers', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 60, verification_status: 'verified' },
  { id: 'asana', name: 'Asana', industry: 'Technology', country: 'USA', remote_policy: 'Remote Flexible', website: 'https://asana.com/jobs', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 63, verification_status: 'verified' },
  { id: 'duolingo', name: 'Duolingo', industry: 'EdTech', country: 'USA', remote_policy: 'Hybrid', website: 'https://careers.duolingo.com', maternity_leave_weeks: 16, paternity_leave_weeks: 16, ivf_coverage: true, fertility_support: true, childcare_support: false, caregiver_leave: false, women_leadership_percent: null, carefolio_score: 61, verification_status: 'verified' },
]

// ── Companies with confirmed public Greenhouse / Lever job boards ─────────────
// These are the companies we actively fetch jobs from.
// Enterprise firms (Deloitte, PwC, McKinsey, Goldman, etc.) use private Workday/SAP
// ATS systems with no public API — they are in COMPANIES above but not fetched here.

const co = (id: string) => {
  const c = COMPANIES.find(c => c.id === id)
  if (!c) throw new Error(`Company not found: ${id}`)
  return c
}

export const ATS_COMPANIES: Array<{ company: Company; ats_type: 'greenhouse' | 'lever'; ats_slug: string }> = [
  { company: co('airbnb'),    ats_type: 'greenhouse', ats_slug: 'airbnb' },
  { company: co('hubspot'),   ats_type: 'greenhouse', ats_slug: 'hubspot' },
  { company: co('etsy'),      ats_type: 'greenhouse', ats_slug: 'etsy' },
  { company: co('stripe'),    ats_type: 'greenhouse', ats_slug: 'stripe' },
  { company: co('twilio'),    ats_type: 'greenhouse', ats_slug: 'twilio' },
  { company: co('gitlab'),    ats_type: 'greenhouse', ats_slug: 'gitlab' },
  { company: co('datadog'),   ats_type: 'greenhouse', ats_slug: 'datadoghq' },
  { company: co('elastic'),   ats_type: 'greenhouse', ats_slug: 'elastic' },
  { company: co('figma'),     ats_type: 'greenhouse', ats_slug: 'figma' },
  { company: co('asana'),     ats_type: 'greenhouse', ats_slug: 'asana' },
  { company: co('duolingo'),  ats_type: 'greenhouse', ats_slug: 'duolingo' },
  { company: co('wise'),      ats_type: 'greenhouse', ats_slug: 'wise' },
  { company: co('canva'),     ats_type: 'greenhouse', ats_slug: 'canva' },
  { company: co('spotify'),   ats_type: 'greenhouse', ats_slug: 'spotify' },
  { company: co('atlassian'), ats_type: 'greenhouse', ats_slug: 'atlassian' },
  { company: co('shopify'),   ats_type: 'greenhouse', ats_slug: 'shopify' },
  { company: co('lululemon'), ats_type: 'greenhouse', ats_slug: 'lululemon' },
  { company: co('patagonia'), ats_type: 'greenhouse', ats_slug: 'patagonia' },
  { company: co('notion'),    ats_type: 'lever',      ats_slug: 'notion' },
]
